version: '2'
services:
  backend:
    build: ./node
    command: ./init.sh
    volumes:
      - ./node:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
  db:
    build: ./mysql
    ports:
      - "4000:4000"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    env_file: .env
